"""Create table

Revision ID: 77a5ccfe5450
Revises: 
Create Date: 2025-05-01 13:59:27.700468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a5ccfe5450'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('winrate', sa.Float(), nullable=False),
    sa.Column('sol_balance', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('rockets', sa.Integer(), nullable=False),
    sa.Column('trade_counts', sa.Integer(), nullable=False),
    sa.Column('profit_trades', sa.Integer(), nullable=False),
    sa.Column('good_profit', sa.Integer(), nullable=False),
    sa.Column('profit_ratio', sa.Float(), sa.Computed('COALESCE(profit_trades::float / NULLIF(trade_counts,0), 0)', persisted=True), nullable=True),
    sa.Column('good_ratio', sa.Float(), sa.Computed('COALESCE(good_profit::float  / NULLIF(trade_counts,0), 0)', persisted=True), nullable=True),
    sa.Column('fast_trades', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('lable', sa.String(), nullable=True),
    sa.Column('checked_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    # ### end Alembic commands ###
